### ISSUE TITLE
Sunspot.index! no longer works after upgrading to 2.2.7

### ISSUE THREAD

**Issue by DmytroStepaniuk** [sunspot/sunspot#856]
After upgrading to version 2.2.7 i'm getting error on Sunspot.index! execution 

```
RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request
Error: {"responseHeader":{"status":400,"QTime":0},"error":{"msg":"Unexpected character '[' (code 91) in prolog; expected '<'\n at [row,col {unknown-source}]: [1,1]","code":400}}
```

Trace: 

```ruby
Backtrace: /app/vendor/bundle/ruby/2.4.0/gems/rsolr-2.0.1/lib/rsolr/client.rb:193:in `rescue in execute'
/app/vendor/bundle/ruby/2.4.0/gems/rsolr-2.0.1/lib/rsolr/client.rb:185:in `execute'
/app/vendor/bundle/ruby/2.4.0/gems/rsolr-2.0.1/lib/rsolr/client.rb:180:in `send_and_receive'
/app/vendor/bundle/ruby/2.4.0/gems/sunspot_rails-2.2.7/lib/sunspot/rails/solr_instrumentation.rb:16:in `block in send_and_receive_with_as_instrumentation'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/notifications.rb:164:in `block in instrument'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/notifications.rb:164:in `instrument'
/app/vendor/bundle/ruby/2.4.0/gems/sunspot_rails-2.2.7/lib/sunspot/rails/solr_instrumentation.rb:15:in `send_and_receive_with_as_instrumentation'
(eval):2:in `post'
/app/vendor/bundle/ruby/2.4.0/gems/rsolr-2.0.1/lib/rsolr/client.rb:83:in `update'
/app/vendor/bundle/ruby/2.4.0/gems/rsolr-2.0.1/lib/rsolr/client.rb:102:in `add'
	from /app/vendor/bundle/ruby/2.4.0/gems/rsolr-2.0.1/lib/rsolr/client.rb:193:in `rescue in execute'
	from /app/vendor/bundle/ruby/2.4.0/gems/rsolr-2.0.1/lib/rsolr/client.rb:185:in `execute'
	from /app/vendor/bundle/ruby/2.4.0/gems/rsolr-2.0.1/lib/rsolr/client.rb:180:in `send_and_receive'
	from /app/vendor/bundle/ruby/2.4.0/gems/sunspot_rails-2.2.7/lib/sunspot/rails/solr_instrumentation.rb:16:in `block in send_and_receive_with_as_instrumentation'
	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/notifications.rb:164:in `block in instrument'
	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/notifications.rb:164:in `instrument'
	from /app/vendor/bundle/ruby/2.4.0/gems/sunspot_rails-2.2.7/lib/sunspot/rails/solr_instrumentation.rb:15:in `send_and_receive_with_as_instrumentation'
	from (eval):2:in `post'
	from /app/vendor/bundle/ruby/2.4.0/gems/rsolr-2.0.1/lib/rsolr/client.rb:83:in `update'
	from /app/vendor/bundle/ruby/2.4.0/gems/rsolr-2.0.1/lib/rsolr/client.rb:102:in `add'
	from /app/vendor/bundle/ruby/2.4.0/gems/sunspot-2.2.7/lib/sunspot/indexer.rb:127:in `add_documents'
	from /app/vendor/bundle/ruby/2.4.0/gems/sunspot-2.2.7/lib/sunspot/indexer.rb:134:in `add_batch_documents'
	from /app/vendor/bundle/ruby/2.4.0/gems/sunspot-2.2.7/lib/sunspot/indexer.rb:26:in `add'
	from /app/vendor/bundle/ruby/2.4.0/gems/sunspot-2.2.7/lib/sunspot/session.rb:91:in `index'
	from /app/vendor/bundle/ruby/2.4.0/gems/sunspot-2.2.7/lib/sunspot/session.rb:98:in `index!'
	from /app/vendor/bundle/ruby/2.4.0/gems/sunspot-2.2.7/lib/sunspot/session_proxy/abstract_session_proxy.rb:11:in `index!'
	from /app/vendor/bundle/ruby/2.4.0/gems/sunspot-2.2.7/lib/sunspot.rb:196:in `index!'
	from (irb):4
```

Downgrading to 2.2.5 helped me. But 2.2.5 has a lot of things that will be deprecated soon.

**Comment by giovannelli** [comment]
Hi @DmytroStepaniuk,
if you force **Rsolr** to the version 1.1.2 it works. 
I'm checking why is not working with the versione 2.0.1

**Comment by DmytroStepaniuk** [comment]
@giovannelli, it still don't work with new rsolr 2.0.2  

```
RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request
Error: {"responseHeader":{"status":400,"QTime":0},"error":{"msg":"Unexpected character '[' (code 91) in prolog; expected '<'\n at [row,col {unknown-source}]: [1,1]","code":400}}
```

**Comment by jormon** [comment]
It's something related to the fact that in version 2+ rsolr generates json requests, not XML based ones:

https://github.com/rsolr/rsolr/blob/master/CHANGES.txt

**Comment by DmytroStepaniuk** [comment]
@jormon, seems like there should be ability of configure which type requests have to be used, right? 

Super strange thing is that nobody else requested the same issue.

**Comment by jormon** [comment]
For now I've fixed with a `gem "rsolr", "<2"` in my Gemfile.

**Comment by DmytroStepaniuk** [comment]
@jormon, i have checked hack in PR and it seems even works. 

If sunspot rails doesn't suppose to work with json, then we should force RSolr client to use only xml. Right?

**Comment by serggl** [comment]
I've posted related issue in rsolr https://github.com/rsolr/rsolr/issues/193
I will also merge #860 and add some tests around this issue

**Comment by serggl** [comment]
ok, I've now opened a PR https://github.com/rsolr/rsolr/pull/194 which should fix the root cause.
fill free do add +1s 😉

**Comment by serggl** [comment]
https://github.com/rsolr/rsolr/pull/194 was merged and released, but Sunspot test suite still fails to pass due to https://github.com/rsolr/rsolr/pull/195

**Comment by serggl** [comment]
so finally it was fixed in `rsolr`, so this issue could be closed. `bundle update rsolr` for anyone who faces this issue

**Comment by rajeev-learningmate** [comment]
Hello All
I am using sunspot_solr (2.2.0) and whenever I am running Model.reindex then it is throwing error like..

irb(main):001:0> Book::Page.reindex
D, [2018-06-05T06:05:33.947926 #6612] DEBUG -- : SOLR Request (8.9ms) [ path=update parameters={} ]
Book::Page Load (0.3ms) SELECT book_pages.* FROM book_pages ORDER BY book_pages.id ASC LIMIT 50
[2018-06-05 06:05:33 +0000] Start Indexing
D, [2018-06-05T06:05:34.506263 #6612] DEBUG -- : SOLR Request (492.7ms) [ path=update parameters={} ]
RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request
Error: {'responseHeader'=>{'status'=>400,'QTime'=>480},'error'=>{'msg'=>'Illegal character ((CTRL-CHAR, code 7))
at [row,col {unknown-source}]: [544,4]','code'=>400}}

URI: http://localhost:8982/solr/development/update?wt=ruby
Request Headers: {"Content-Type"=>"text/xml"}
Request Data: "<f

**Comment by DmytroStepaniuk** [comment]
@rajeev-learningmate 

You can🐒-patch it by your own 😂 

Check out this one - https://github.com/sunspot/sunspot/pull/860/files

But, this PR was already merged into master 

https://github.com/sunspot/sunspot/commit/72a6cb257ef44c969333a02486bf8bef0beb2146

**Comment by elalemanyo** [comment]
I have the same issue even I am using the last versions:
```
ruby '2.5.1'

gem 'sunspot_rails', '2.5.0'
```
and I also add `update_format: json` to my `sunspot.yml`

The error that I get is:
```
RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request
Error: {"responseHeader":{"status":400,"QTime":0},"error":{"msg":"Unexpected character '[' (code 91) in prolog; expected '<'\n at [row,col {unknown-source}]: [1,1]","code":400}}
```

**Comment by mlh758** [comment]
What version of rsolr is in your Gemfile.lock?

**Comment by elalemanyo** [comment]
@mlh758 `rsolr (2.2.1)`

**Comment by mlh758** [comment]
If you're using `sunspot_rails` instead of a standalone or Docker version that means you're probably on solr 5.x. Does that even support json payloads?

**Comment by elalemanyo** [comment]
@mlh758 We are using `4.10.2` 🙈

**Comment by mlh758** [comment]
If you're using `sunspot_rails` in production you should really check out the documentation [here](https://github.com/sunspot/sunspot#running-solr-in-production-environment).
